[project]
name = "defin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi-users>=15.0.4",
    "fastapi[standard]>=0.128.5",
    "python-dotenv>=1.2.1",
]
